<a href="https://colab.research.google.com/github/smritigithubacc/Deep-learning-projects/blob/main/Customer_churn_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as  np


In [ ]:
df=pd.read_csv('Churn_Modelling.csv')

In [ ]:
df.head(5)


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df.drop(columns=['RowNumber','CustomerId','Surname'],axis=1,inplace=True)
df.head(5)



CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [ ]:
df=pd.get_dummies(df,columns=['Gender','Geography'])

In [ ]:
print(df)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Gender_Female  Gender_Male  \
0                  1        101348.88       1              1          

In [ ]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
X

array([[619.,  42.,   2., ...,   0.,   1.,   0.],
       [608.,  41.,   1., ...,   0.,   0.,   0.],
       [502.,  42.,   8., ...,   0.,   1.,   0.],
       ...,
       [709.,  36.,   7., ...,   0.,   1.,   0.],
       [772.,  42.,   3., ...,   1.,   0.,   1.],
       [792.,  28.,   4., ...,   0.,   1.,   0.]])

In [ ]:
y

array([0, 1, 0, ..., 0, 0, 0], dtype=uint8)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model=Sequential()
model.add(Dense(11,activation='sigmoid',input_dim=11))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train,y_train,batch_size=50,epochs=100)

Epoch 1/100
160/160 [==============================] - 1s 2ms/step - loss: 0.8317 - accuracy: 0.3950
Epoch 2/100
160/160 [==============================] - 0s 2ms/step - loss: 0.6403 - accuracy: 0.6219
Epoch 3/100
160/160 [==============================] - 0s 2ms/step - loss: 0.5916 - accuracy: 0.7085
Epoch 4/100
160/160 [==============================] - 0s 2ms/step - loss: 0.5764 - accuracy: 0.7524
Epoch 5/100
160/160 [==============================] - 0s 2ms/step - loss: 0.5705 - accuracy: 0.7524
Epoch 6/100
160/160 [==============================] - 0s 2ms/step - loss: 0.5659 - accuracy: 0.7524
Epoch 7/100
160/160 [==============================] - 0s 2ms/step - loss: 0.5604 - accuracy: 0.7524
Epoch 8/100
160/160 [==============================] - 0s 2ms/step - loss: 0.5582 - accuracy: 0.7524
Epoch 9/100
160/160 [==============================] - 0s 2ms/step - loss: 0.5567 - accuracy: 0.7524
Epoch 10/100
160/160 [==============================] - 0s 2ms/step - loss: 0.5554 - accura

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (50, 11)                  154       
                                                                 
 dense_1 (Dense)             (50, 1)                   12        
                                                                 
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.layers[0].get_weights()

[array([[-1.43926647e-02,  9.50094014e-02,  3.34608136e-03,
         -1.41784374e-03,  3.68460687e-03,  9.60865524e-04,
         -5.12915337e-03,  4.31188196e-03,  2.84330361e-03,
         -7.76786311e-03,  4.96639498e-02],
        [-7.46342074e-03,  2.42108181e-02,  3.03857331e-03,
          2.65541300e-02,  5.67221409e-03,  8.52064788e-03,
         -4.75908909e-03,  2.68515497e-02, -7.86119513e-03,
          4.35305424e-02,  1.16146691e-02],
        [ 3.47784208e-03, -5.86298108e-03, -2.21205298e-02,
          1.00720990e-02,  5.43395756e-03,  1.42723657e-02,
         -5.22862934e-03,  4.83877352e-03, -3.82043328e-03,
          3.02928891e-02,  1.28558055e-02],
        [ 6.44662753e-02,  1.97145671e-01,  6.53252900e-02,
          3.39105390e-02, -3.23638916e-02, -9.69632044e-02,
         -7.42996624e-03, -6.56075552e-02,  3.04219928e-02,
          7.66558871e-02,  5.05095348e-02],
        [ 2.93911081e-02,  5.32614328e-02, -3.87768075e-03,
          2.31563915e-02, -2.41423515e-03, -

In [ ]:
y_pred=model.predict(X_test)

63/63 [==============================] - 0s 1ms/step


In [ ]:
y_pred = y_pred.argmax(axis=-1)

In [ ]:
predictions=np.where(y_pred>0.5,1,0)



In [ ]:
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
#to improve accuracy increase hidden layers,change activation function to relu,increase number of epochs

0.752